linters:
  enable:
    - gocyclo
    - gocognit
    - lll
    - nlreturn
    - errname
    - errcheck
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  gocognit:
    min-complexity: 10
  gocyclo:
    min-complexity: 10

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false